-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'


hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl setcursor Bibata-Original-Classic 24")
end)
