-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local terminal = "kitty"

local fileManager = "thunar"

local menu = "wofi --show drun"

local navigator = "chromium"


--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

hl.bind("F7", hl.dsp.exec_cmd(navigator))

hl.bind("XF86Launch9", hl.dsp.exec_cmd(navigator))

hl.bind("XF86LaunchA", hl.dsp.exec_cmd(terminal))

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "return", hl.dsp.exec_cmd(terminal))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd(fileManager))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "O", hl.dsp.layout("togglesplit"))

-- Toggle window group

hl.bind(mainMod .. " + " .. "T", hl.dsp.layout("swapsplit"))

-- Swapsplit

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "h", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "l", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "k", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "j", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "comma", hl.dsp.layout("splitratio", -0.1))

-- [hidden]

hl.bind(mainMod .. " + " .. "semicolon", hl.dsp.layout("splitratio", "+0.1"))

-- [hidden]

--/# bind = Super+Shift, ←/↑/→/↓,, # Window: move in direction

hl.bind("SUPER + SHIFT" .. " + " .. "Left", hl.dsp.focus({ direction = "l" }))

-- [hidden]

hl.bind("SUPER + SHIFT" .. " + " .. "Right", hl.dsp.focus({ direction = "r" }))

-- [hidden]

hl.bind("SUPER + SHIFT" .. " + " .. "Up", hl.dsp.focus({ direction = "u" }))

-- [hidden]

hl.bind("SUPER + SHIFT" .. " + " .. "Down", hl.dsp.focus({ direction = "d" }))

-- [hidden]

hl.bind("SUPER + SHIFT" .. " + " .. "h", hl.dsp.focus({ direction = "l" }))

-- [hidden]

hl.bind("SUPER + SHIFT" .. " + " .. "l", hl.dsp.focus({ direction = "r" }))

-- [hidden]

hl.bind("SUPER + SHIFT" .. " + " .. "k", hl.dsp.focus({ direction = "u" }))

-- [hidden]

hl.bind("SUPER + SHIFT" .. " + " .. "j", hl.dsp.focus({ direction = "d" }))

-- [hidden]

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. "ampersand", hl.dsp.focus({ workspace = 1 }))

-- Open workspace 1

hl.bind(mainMod .. " + " .. "eacute", hl.dsp.focus({ workspace = 2 }))

-- Open workspace 2

hl.bind(mainMod .. " + " .. "quotedbl", hl.dsp.focus({ workspace = 3 }))

-- Open workspace 3

hl.bind(mainMod .. " + " .. "apostrophe", hl.dsp.focus({ workspace = 4 }))

-- Open workspace 4

hl.bind(mainMod .. " + " .. "parenleft", hl.dsp.focus({ workspace = 5 }))

-- Open workspace 5

hl.bind(mainMod .. " + " .. "egrave", hl.dsp.focus({ workspace = 6 }))

-- Open workspace 6

hl.bind(mainMod .. " + " .. "minus", hl.dsp.focus({ workspace = 7 }))

-- Open workspace 7

hl.bind(mainMod .. " + " .. "underscore", hl.dsp.focus({ workspace = 8 }))

-- Open workspace 8

hl.bind(mainMod .. " + " .. "ccedilla", hl.dsp.focus({ workspace = 9 }))

-- Open workspace 9

hl.bind(mainMod .. " + " .. "agrave", hl.dsp.focus({ workspace = 10 }))

-- Open workspace 10

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "ampersand", hl.dsp.window.move({ workspace = 1 }))

-- Move active window to workspace 1

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "eacute", hl.dsp.window.move({ workspace = 2 }))

-- Move active window to workspace 2

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "quotedbl", hl.dsp.window.move({ workspace = 3 }))

-- Move active window to workspace 3

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "apostrophe", hl.dsp.window.move({ workspace = 4 }))

-- Move active window to workspace 4

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "parenleft", hl.dsp.window.move({ workspace = 5 }))

-- Move active window to workspace 5

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "minus", hl.dsp.window.move({ workspace = 6 }))

-- Move active window to workspace 6

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "egrave", hl.dsp.window.move({ workspace = 7 }))

-- Move active window to workspace 7

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "underscore", hl.dsp.window.move({ workspace = 8 }))

-- Move active window to workspace 8

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "ccedilla", hl.dsp.window.move({ workspace = 9 }))

-- Move active window to workspace 9

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "agrave", hl.dsp.window.move({ workspace = 10 }))

-- Move active window to workspace 10

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen({mode="maximized"}))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "Tab", hl.dsp.focus({ workspace = "m+1" }))

-- Open next workspace

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Tab", hl.dsp.focus({ workspace = "m-1" }))

-- Open previous workspace

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.focus({ workspace = "empty" }))

-- Open the next empty workspace

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"), { locked = true })

-- Brightness raise

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness raise"), { locked = true })

-- Brightness lower

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness lower"), { locked = true })

hl.bind("CAPS" .. " + " .. "Caps_Lock", hl.dsp.exec_cmd("swayosd-client --caps-lock"), { repeating = true })

-- Requires playerctl

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind("CTRL" .. " + " .. "PRIOR", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind("CTRL" .. " + " .. "NEXT", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("PRINT", hl.dsp.exec_cmd("grim -g \"$(slurp)\"-| swappy -f-"))

hl.bind("F8", hl.dsp.exec_cmd("grim -g \"$(slurp)\"-| swappy -f-"))
