-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "preferred",
    position = "0x0",
    scale    = "auto",
})

hl.monitor({
    output   = "DVI-D-1",
    mode     = "preferred",
    position = "2560x0",
    scale    = "auto",
})
