-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

hl.workspace_rule({
    workspace = 1,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DVI-D-1",
})

-- Ignore maximize requests from apps. You'll probably like this.

hl.window_rule({
    name  = "windowrule-1",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland

hl.window_rule({
    name  = "windowrule-2",
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    no_focus = true,
})

hl.window_rule({
    name  = "windowrule-3",
    match = {
        title = "^(blueberry.py)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-4",
    match = {
        title = "^(steam)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-5",
    match = {
        title = "^(Calculatrice)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-6",
    match = {
        title = "^(galculator)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-7",
    match = {
        title = "^(guifetch)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-8",
    match = {
        class = "(dev.warp.Warp)",
    },
    tile = true,
})

hl.window_rule({
    name  = "windowrule-9",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-10",
    match = {
        title = "^(Open File)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    name  = "windowrule-11",
    match = {
        title = "^(Select a File)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    name  = "windowrule-12",
    match = {
        title = "^(Choose wallpaper)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    name  = "windowrule-13",
    match = {
        title = "^(Open Folder)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    name  = "windowrule-14",
    match = {
        title = "^(Save As)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    name  = "windowrule-15",
    match = {
        title = "^(Library)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    name  = "windowrule-16",
    match = {
        title = "^(File Upload)(.*)$",
    },
    center = true,
    float = true,
})

-- Picture-in-Picture

--

hl.window_rule({
    name  = "windowrule-17",
    match = {
        title = "^(Picture(-| )in(-| )[Pp]icture)$",
    },
    keep_aspect_ratio = true,
    move = { "((monitor_w*0.73))", "((monitor_h*0.72))" },
    size = {"(monitor_w*0.25)","window_h"},
    float = true,
    pin = true,
})

--no opacity on firefox

hl.window_rule({
    name  = "windowrule-18",
    match = {
        class = "^firefox.*$",
    },
    opacity = '1 1 override 1 override'
})

hl.window_rule({
    name  = "windowrule-19",
    match = {
        class = "^(chromium)$",
    },
    opacity =  "1 1 override 1 override" ,
})

hl.window_rule({
    name  = "windowrule-20",
    match = {
        class = "^mpv.*$",
    },
    opacity =  "1 1 override 1 override",
})

-- Dialogs
