

#██████╗ ███████╗███████╗████████╗███████╗
#██╔══██╗██╔════╝██╔════╝╚══██╔══╝██╔════╝
#██████╔╝█████╗  █████╗     ██║   ███████╗
#██╔══██╗██╔══╝  ██╔══╝     ██║   ╚════██║
#██████╔╝███████╗███████╗   ██║   ███████║
#╚═════╝ ╚══════╝╚══════╝   ╚═╝   ╚══════╝
                                         



directory: /mnt/diskstation/music
library:  ~/Sync/library.db
import:
        move: yes
        write: yes
        log: ~/Sync/import.log
        
paths:
        default: $albumartist/$album%aunique{}/$track - $title 
        albumtype:classical: classical/$album%aunique{}/$track-$artist-$title 
        albumtype:Soundtrack: soundtracks/$album%aunique{}/$track-$artist-$title 
        comp: Compilations/$album%aunique{}/$track-$artist-$title
        genre:classical: classical/$artist-$title
        genre:Soundtrack: soundtracks/$artist-$title

        singleton: $artist/$title
      

plugins: fetchart  lastgenre fromfilename chroma web convert info mpdupdate rewrite missing

rewrite:
  artist .*Gorillaz.*: Gorillaz

convert:
    auto: yes 
    never_convert_lossy_files: yes
    format: mp3
    formats:
      mp3: ffmpeg -i $source -y -vn -aq 0 $dest
lastgenre:
        source: track

acoustid:
  apikey: KPkFBJ4dVd
fetchart:
        auto: yes

chroma:
       auto: yes

threaded: yes

mpd:
  host: localhost
  port: 6600
